"""Add gemini_summary to AnalysisRecord

Revision ID: 735e05694139
Revises: 6419b0be64b6
Create Date: 2026-06-19 00:21:38.979132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735e05694139'
down_revision: Union[str, Sequence[str], None] = '6419b0be64b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_records', sa.Column('gemini_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_records', 'gemini_summary')
    # ### end Alembic commands ###
